version: "3"
services:
  web:
    container_name: djang-blog-it
    restart: always
    image: django
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
#    links:
#      - db
#  db:
#    container_name: "blog_it_db"
#    image: mysql
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD='root'
#      - MYSQL_ROOT_HOST=%.%.%.%
