version: "3"
services:
  blog_it:
    image: mysql/mysql-server:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: cuong
      MYSQL_PASSWORD: cuong
      MYSQL_DATABASE: blog_it
    volumes:
      - .:/db
  web:
    links:
      - blog_it
    image: django
    ports:
      - 8080:8000
    build:
      context: .
      dockerfile: Dockerfile