version: "3"
services:
  blog_it:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cuong
      POSTGRES_PASSWORD: cuong
      POSTGRES_DB: blog_it
    volumes:
    - .:/db
  web:
    links:
      - blog_it
    image: django
    ports:
      - 8080:8000
    build:
      context: .
      dockerfile: Dockerfile

